"""Add HistoricalScheme model

Revision ID: 15485971f6ab
Revises: 3c1c20ede17a
Create Date: 2026-09-30 15:46:35.171098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15485971f6ab'
down_revision: Union[str, Sequence[str], None] = '3c1c20ede17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_source_identifier', sa.String(), nullable=True),
    sa.Column('budget_scheme_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('objectives', sa.String(), nullable=True),
    sa.Column('target_beneficiaries', sa.String(), nullable=True),
    sa.Column('sector_category', sa.String(), nullable=True),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('is_uncertain_match', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['budget_scheme_id'], ['budget_schemes.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['budget_departments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['budget_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_name', 'department_id', 'financial_year', 'source_document_id', name='uq_historical_scheme')
    )
    op.create_index(op.f('ix_historical_schemes_budget_scheme_id'), 'historical_schemes', ['budget_scheme_id'], unique=False)
    op.create_index(op.f('ix_historical_schemes_department_id'), 'historical_schemes', ['department_id'], unique=False)
    op.create_index(op.f('ix_historical_schemes_financial_year'), 'historical_schemes', ['financial_year'], unique=False)
    op.create_index(op.f('ix_historical_schemes_id'), 'historical_schemes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_schemes_id'), table_name='historical_schemes')
    op.drop_index(op.f('ix_historical_schemes_financial_year'), table_name='historical_schemes')
    op.drop_index(op.f('ix_historical_schemes_department_id'), table_name='historical_schemes')
    op.drop_index(op.f('ix_historical_schemes_budget_scheme_id'), table_name='historical_schemes')
    op.drop_table('historical_schemes')
    # ### end Alembic commands ###
