"""create_budget_schema

Revision ID: 3c1c20ede17a
Revises: 
Create Date: 2026-09-27 11:39:55.854004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1c20ede17a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_departments_code'), 'budget_departments', ['code'], unique=False)
    op.create_index(op.f('ix_budget_departments_id'), 'budget_departments', ['id'], unique=False)
    op.create_index(op.f('ix_budget_departments_name'), 'budget_departments', ['name'], unique=True)
    op.create_table('budget_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_import_batches_id'), 'budget_import_batches', ['id'], unique=False)
    op.create_table('budget_source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifest_dataset_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('official_source_url', sa.String(), nullable=True),
    sa.Column('financial_year_coverage', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_source_documents_id'), 'budget_source_documents', ['id'], unique=False)
    op.create_index(op.f('ix_budget_source_documents_manifest_dataset_id'), 'budget_source_documents', ['manifest_dataset_id'], unique=True)
    op.create_table('modelevaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('evaluation_metric', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('dataset_reference', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelevaluation_id'), 'modelevaluation', ['id'], unique=False)
    op.create_index(op.f('ix_modelevaluation_model_name'), 'modelevaluation', ['model_name'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=False)
    op.create_table('budget_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_of_account', sa.String(), nullable=True),
    sa.Column('normalized_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['budget_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name', 'head_of_account', name='uq_budget_scheme')
    )
    op.create_index(op.f('ix_budget_schemes_head_of_account'), 'budget_schemes', ['head_of_account'], unique=False)
    op.create_index(op.f('ix_budget_schemes_id'), 'budget_schemes', ['id'], unique=False)
    op.create_index(op.f('ix_budget_schemes_name'), 'budget_schemes', ['name'], unique=False)
    op.create_table('datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_id'), 'datasource', ['id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_table('budget_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('financial_year', sa.String(), nullable=False),
    sa.Column('budget_stage', sa.Enum('budget_estimate', 'revised_estimate', 'actual_expenditure', name='budgetstage'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency_unit', sa.String(), nullable=False),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('original_category_text', sa.String(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['budget_import_batches.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['budget_schemes.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['budget_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'financial_year', 'budget_stage', 'source_document_id', name='uq_budget_record_entry')
    )
    op.create_index(op.f('ix_budget_records_budget_stage'), 'budget_records', ['budget_stage'], unique=False)
    op.create_index(op.f('ix_budget_records_financial_year'), 'budget_records', ['financial_year'], unique=False)
    op.create_index(op.f('ix_budget_records_id'), 'budget_records', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('supporting_values', sa.JSON(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=True),
    sa.Column('result_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['datasource.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('modelprediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('prediction_data', sa.JSON(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelprediction_id'), 'modelprediction', ['id'], unique=False)
    op.create_index(op.f('ix_modelprediction_model_name'), 'modelprediction', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelprediction_model_name'), table_name='modelprediction')
    op.drop_index(op.f('ix_modelprediction_id'), table_name='modelprediction')
    op.drop_table('modelprediction')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_budget_records_id'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_financial_year'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_budget_stage'), table_name='budget_records')
    op.drop_table('budget_records')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_datasource_id'), table_name='datasource')
    op.drop_table('datasource')
    op.drop_index(op.f('ix_budget_schemes_name'), table_name='budget_schemes')
    op.drop_index(op.f('ix_budget_schemes_id'), table_name='budget_schemes')
    op.drop_index(op.f('ix_budget_schemes_head_of_account'), table_name='budget_schemes')
    op.drop_table('budget_schemes')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_modelevaluation_model_name'), table_name='modelevaluation')
    op.drop_index(op.f('ix_modelevaluation_id'), table_name='modelevaluation')
    op.drop_table('modelevaluation')
    op.drop_index(op.f('ix_budget_source_documents_manifest_dataset_id'), table_name='budget_source_documents')
    op.drop_index(op.f('ix_budget_source_documents_id'), table_name='budget_source_documents')
    op.drop_table('budget_source_documents')
    op.drop_index(op.f('ix_budget_import_batches_id'), table_name='budget_import_batches')
    op.drop_table('budget_import_batches')
    op.drop_index(op.f('ix_budget_departments_name'), table_name='budget_departments')
    op.drop_index(op.f('ix_budget_departments_id'), table_name='budget_departments')
    op.drop_index(op.f('ix_budget_departments_code'), table_name='budget_departments')
    op.drop_table('budget_departments')
    # ### end Alembic commands ###
