"""create historical scheme database

Revision ID: 7ccfdea60b7f
Revises: 15485971f6ab
Create Date: 2026-10-03 12:47:09.983587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccfdea60b7f'
down_revision: Union[str, Sequence[str], None] = '15485971f6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_categories_id'), 'scheme_categories', ['id'], unique=False)
    op.create_index(op.f('ix_scheme_categories_name'), 'scheme_categories', ['name'], unique=True)
    op.create_table('scheme_similarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_scheme_id', sa.Integer(), nullable=False),
    sa.Column('target_scheme_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_scheme_id'], ['historical_schemes.id'], ),
    sa.ForeignKeyConstraint(['target_scheme_id'], ['historical_schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_scheme_id', 'target_scheme_id', 'model_version', name='uq_scheme_similarity')
    )
    op.create_index(op.f('ix_scheme_similarities_id'), 'scheme_similarities', ['id'], unique=False)
    op.create_index(op.f('ix_scheme_similarities_similarity_score'), 'scheme_similarities', ['similarity_score'], unique=False)
    op.create_index(op.f('ix_scheme_similarities_source_scheme_id'), 'scheme_similarities', ['source_scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_similarities_target_scheme_id'), 'scheme_similarities', ['target_scheme_id'], unique=False)
    op.create_table('scheme_source_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historical_scheme_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['historical_scheme_id'], ['historical_schemes.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['budget_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('historical_scheme_id', 'source_document_id', name='uq_scheme_source_rel')
    )
    op.create_index(op.f('ix_scheme_source_relationships_historical_scheme_id'), 'scheme_source_relationships', ['historical_scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_source_relationships_id'), 'scheme_source_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_scheme_source_relationships_source_document_id'), 'scheme_source_relationships', ['source_document_id'], unique=False)
    with op.batch_alter_table('historical_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))
        batch_op.drop_constraint('uq_historical_scheme', type_='unique')
        batch_op.create_unique_constraint('uq_historical_scheme', ['scheme_name', 'department_id', 'financial_year'])
        batch_op.create_index(batch_op.f('ix_historical_schemes_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_hist_scheme_category', 'scheme_categories', ['category_id'], ['id'])
        batch_op.drop_column('source_document_id')
        batch_op.drop_column('source_page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_page_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('source_document_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_hist_scheme_category', type_='foreignkey')
        batch_op.create_foreign_key('fk_hist_scheme_source', 'budget_source_documents', ['source_document_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_historical_schemes_category_id'))
        batch_op.drop_constraint('uq_historical_scheme', type_='unique')
        batch_op.create_unique_constraint('uq_historical_scheme', ['scheme_name', 'department_id', 'financial_year', 'source_document_id'])
        batch_op.drop_column('embedding')
        batch_op.drop_column('category_id')
    op.drop_index(op.f('ix_scheme_source_relationships_source_document_id'), table_name='scheme_source_relationships')
    op.drop_index(op.f('ix_scheme_source_relationships_id'), table_name='scheme_source_relationships')
    op.drop_index(op.f('ix_scheme_source_relationships_historical_scheme_id'), table_name='scheme_source_relationships')
    op.drop_table('scheme_source_relationships')
    op.drop_index(op.f('ix_scheme_similarities_target_scheme_id'), table_name='scheme_similarities')
    op.drop_index(op.f('ix_scheme_similarities_source_scheme_id'), table_name='scheme_similarities')
    op.drop_index(op.f('ix_scheme_similarities_similarity_score'), table_name='scheme_similarities')
    op.drop_index(op.f('ix_scheme_similarities_id'), table_name='scheme_similarities')
    op.drop_table('scheme_similarities')
    op.drop_index(op.f('ix_scheme_categories_name'), table_name='scheme_categories')
    op.drop_index(op.f('ix_scheme_categories_id'), table_name='scheme_categories')
    op.drop_table('scheme_categories')
    # ### end Alembic commands ###
